# Generated by Django 3.1.2 on 2021-11-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20211127_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
